# An Intro to NumPy
---

Created by Krishna Patel (kpatel7@stanford.edu)

Updated by Bryan Kim (bskim96@stanford.edu)

Some examples based on the NumPy tutorial by Justin Johnson for CS 231n.

## Why NumPy

NumPy is a very popular Python library used for matrix operations and linear
algebra. The purpose of this notebook is to give a basic introduction to
NumPy for students who haven't used it before, and an easy review for those who
have.

Learning NumPy is well worth the effort, as you'll be using it constantly if
you choose to take further ML/AI courses at Stanford.

This notebook is optional and ungraded, so if you've worked with NumPy before
and feel comfortable working with it, feel free to skim it or skip it.

If NumPy is new to you, hopefully it helps get you started working with it.

### Environment Check

Before proceeding, run the cell below to check that you're using the right
conda environment (with NumPy installed).

In [ ]:
import os
assert os.environ['CONDA_DEFAULT_ENV'] == "cs124"

import sys
assert sys.version_info.major == 3 and sys.version_info.minor == 8

If the above cell complains, it means that you're using the wrong environment
or Python version!

If so, please exit this notebook, kill the notebook server with CTRL-C, and
try running

$ conda activate cs124

then restarting your notebook server with

$ jupyter notebook

## Exercises

### Exercise 1 -- Basic NumPy

In [1]:
# Let's import numpy (aliasing the import as np is traditional)
import numpy as np

The basic building blocks of NumPy are arrays, which are represented with the
`np.ndarray` type. Arrays represent multi-dimensional matrices (often also
referred to as tensors).

We can easily create a 1-D array (a vector) by calling `np.array()` and passing
in a Python list with the data that should go into the array:

In [2]:
# This is an array (of type np.ndarray)
a = np.array([1, 2, 3, 4, 5])

print("a is an: {}".format(type(a)))
a

a is an: <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

Arrays can have different numbers of dimensions, different shapes, and contain
elements of different types. Very frequently you'll want to check these
properties (especially shape), which you can do like this:

In [4]:
# a is an array containing integers (in this case, 64-bit integers)
print("Data type of a: {}".format(a.dtype))

# a is a 1-dimensional array of length 5
print("Shape of a: {}".format(a.shape))

Data type of a: int64
Shape of a: (5,)


In [6]:
# Note that b contains floating point numbers, not integers
b = np.array([5.0, 1.0])

print("Data type of b: {}".format(b.dtype))
print("Shape of b: {}".format(b.shape))
b

Data type of b: float64
Shape of b: (2,)


array([5., 1.])

As we noted above, you can initialize a 1-D array with a python list. However,
most of the time we're interested in higher-dimensional arrays like 2-D arrays
(matrices). You can initialize them using nested Python lists:

In [7]:
# A 2-D array
c = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Shape of c: {}".format(c.shape))
c

Shape of c: (3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

Note that the length of the __outer__ list is the first dimension (in this
case of length 3), while the lengths of the __inner__ lists are the second
dimension (in this case of length 2).

It's easy to get your dimensions/shapes mixed up if you get the order confused.
Just remember that the number of (horizontal) rows is always the first
dimension, and the number of (vertical) columns is the second dimension.

In addition to the basic `np.array`, NumPy provides a bunch of other convenient
methods to create different types of arrays/matrices (to save you from
typing out the data by hand, or having to use loops or Python list
comprehensions). Some useful ones include:

In [15]:
# To create an all-zero array with the given shape (3, 4)
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# To create an all-ones array
ones = np.ones((2, 2))
ones

array([[1., 1.],
       [1., 1.]])

In [17]:
# To create an uninitialized array (junk values). This is useful if you know
# you're going to manually fill/overwrite the entire array anyways (it saves
# the time NumPy would have spent to set every entry to a particular value)
# NOTE: Do NOT confuse this with np.zeros(). "empty" does not mean all zeroes,
# it just means we don't care what is in it. It could be all zeros, it could
# be all ones, it could be anything at all.
empty = np.empty((2, 2))
empty

array([[1., 1.],
       [1., 1.]])

In [18]:
# To create an array filled with a single value
filled = np.full((3, 3), 5)
filled

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [19]:
# To create an identity matrix
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# To create an array filled with random values sampled uniformly
# from [0.0, 1.0)
random = np.random.random((2, 2))
random

array([[0.13933868, 0.28391671],
       [0.46481011, 0.59673683]])

Finally, once we have an array that we've initialized with data, we can also
reshape it without changing its data using np.reshape!

Check out this example:

In [21]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print("a.shape = {}".format(a.shape))
a

a.shape = (2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a_reshaped = a.reshape((3, 2))
print("a_reshaped.shape = {}".format(a_reshaped.shape))
a_reshaped

a_reshaped.shape = (3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a_reshaped = a.reshape((6,))
print("a_reshaped.shape = {}".format(a_reshaped.shape))
a_reshaped

a_reshaped.shape = (6,)


array([1, 2, 3, 4, 5, 6])

In [24]:
# Note what happens if we try to reshape to a shape with a different number
# of elements:
a_reshaped = a.reshape((7,))

ValueError: cannot reshape array of size 6 into shape (7,)

### Exercise 2 -- Indexing and slicing

Arrays can be initialized with lists, as we saw, and in many ways they behave
a lot like Python lists! You can access specific elements by their index
(starting with zero, just like in Python lists), and modify them:

In [25]:
a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

In [26]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [27]:
# You can access elements in an array like a Python list by indexing:
print("a[0] = {}".format(a[0]))
print("a[3] = {}".format(a[3]))

a[0] = 1.0
a[3] = 4.0


In [28]:
# You can index into higher-dimensional arrays the same way.

# NOTE: If you had nested python lists instead of a NumPy array, you'd
# need to do something like b[0][1] instead of b[0, 1], so it's a little
# different, but the idea is the same.
print("b[0, 0] = {}".format(b[0, 0]))
print("b[2, 2] = {}".format(b[2, 2]))
print("b[1, 2] = {}".format(b[1, 2]))

b[0, 0] = 1
b[2, 2] = 9
b[1, 2] = 6


In [29]:
# You can also modify elements just like in a Python list
print("a before:\n {}\n".format(a))
a[2] = 9.0
print("a after:\n {}\n".format(a))

a before:
 [1. 2. 3. 4. 5.]

a after:
 [1. 2. 9. 4. 5.]



NumPy also supports more complex forms of indexing (like slicing), which
also behaves similarly to Python lists:

In [30]:
# This is just a Python list for comparison
example_list = [1, 2, 3, 4, 5, 6]

In [31]:
# Recall how we can slice a Python list

# This gives a slice containing every element starting from position/index 1
# (inclusive) up to but EXCLUDING the element at position/index 3
print("example_list[1:3] = {}".format(example_list[1:3]))

# You can also omit the start and end index and it will use the start/end of the
# list instead
print("example_list[:3] = {}".format(example_list[:3]))
print("example_list[1:] = {}".format(example_list[1:]))
print("example_list[:] = {}".format(example_list[:]))

example_list[1:3] = [2, 3]
example_list[:3] = [1, 2, 3]
example_list[1:] = [2, 3, 4, 5, 6]
example_list[:] = [1, 2, 3, 4, 5, 6]


In [32]:
# NumPy works exactly the same way

a = np.array([1, 2, 3, 4, 5, 6])

In [33]:
print("a[1:3] = {}".format(a[1:3]))
print("a[:3] = {}".format(a[:3]))
print("a[1:] = {}".format(a[1:]))
print("a[1:] = {}".format(a[:]))

a[1:3] = [2 3]
a[:3] = [1 2 3]
a[1:] = [2 3 4 5 6]
a[1:] = [1 2 3 4 5 6]


In [34]:
# index with a list
a[[1,3,4]]

array([2, 4, 5])

We can modify slices just like how we modified elements using indexing:

In [35]:
print("a before:\n {}\n".format(a))
a[1:3] = [8, 9]
print("a after:\n {}\n".format(a))

a before:
 [1 2 3 4 5 6]

a after:
 [1 8 9 4 5 6]



We can also slice multi-dimensional arrays. Try to figure out what each
of the expression below will give before running them, to check your
intuition:

In [36]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [37]:
print("b[:, :] =>\n {}\n".format(b[:, :]))
print("b[1, :] =>\n {}\n".format(b[1, :]))

# Note that 1-D arrays are always treated as row vectors (horizontal)
print("b[:, 0] =>\n {}\n".format(b[:, 0]))
print("b[1, :2] =>\n {}\n".format(b[1, :2]))

b[:, :] =>
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[1, :] =>
 [4 5 6]

b[:, 0] =>
 [1 4 7]

b[1, :2] =>
 [4 5]



In [38]:
# Modifying a slice of a 2-D arrays

print("b before:\n {}\n".format(b))
b[:, 0] = 0
print("b after:\n {}\n".format(b))

b before:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

b after:
 [[0 2 3]
 [0 5 6]
 [0 8 9]]



It's important to think carefully about the shapes/dimensions of the slices
that you extract. Depending on how you slice, your result could have fewer
dimensions than the original array, or the same number.

Think about what shapes you'd expect these slices to be,
then run the cell below to double-check:

Do the results make sense to you? If not, can you figure out why the shapes came
out as they did?

In [39]:
print("shape(b[:, :]) = {}".format(b[:, :].shape))
print("shape(b[1, :]) = {}".format(b[1, :].shape))
print("shape(b[1:2, :]) = {}".format(b[1:2, :].shape))
print("shape(b[:, 0]) = {}".format(b[:, 0].shape))
print("shape(b[:, 0:1]) = {}".format(b[:, 0:1].shape))

shape(b[:, :]) = (3, 3)
shape(b[1, :]) = (3,)
shape(b[1:2, :]) = (1, 3)
shape(b[:, 0]) = (3,)
shape(b[:, 0:1]) = (3, 1)


### Exercise 3 -- Array Math and Functions

We covered creating arrays and reading/writing elements in them, but the main
reason we use NumPy in the first place is to do math with arrays (linear
algebra). For the most part, array/vector math in NumPy is extremely
straight-forward and intuitive. You can add, subtract, multiply, etc. NumPy
arrays just like they were Python numbers and NumPy will take care of everything
for you!

For example:

In [40]:
a = np.array([[1,2],
              [3,4]])

In [41]:
b = np.array([[3,3],
              [4,4]])


Note that for all the below element-wise operations, the two
arrays being added/subtracted/multiplied etc. must have the same shape!
(we'll talk about an exception to this rule in the next exercise)

Also note that for many matrix operations, there's two ways of
writing it in NumPy. Either you can call a dedicated function, or you
can use the standard "+, -, *, /" operators on NumPy arrays as if
they were just numbers

In [42]:
# To take an element-wise sum
print("a + b =>\n {}\n".format(a + b))
print("np.add(a, b) =>\n {}\n".format(np.add(a, b)))

# To take an element-wise difference
print("b - a =>\n {}\n".format(b - a))
print("np.subtract(b, a) =>\n {}\n".format(np.subtract(b, a)))

# To take an element-wise product
print("a * b =>\n {}\n".format(a * b))
print("np.multiply(a, b) =>\n {}\n".format(np.multiply(a, b)))

# To take an element-wise quotient
print("a / b =>\n {}\n".format(a / b))
print("np.divide(a, b) =>\n {}\n".format(np.divide(a, b)))

a + b =>
 [[4 5]
 [7 8]]

np.add(a, b) =>
 [[4 5]
 [7 8]]

b - a =>
 [[2 1]
 [1 0]]

np.subtract(b, a) =>
 [[2 1]
 [1 0]]

a * b =>
 [[ 3  6]
 [12 16]]

np.multiply(a, b) =>
 [[ 3  6]
 [12 16]]

a / b =>
 [[0.33333333 0.66666667]
 [0.75       1.        ]]

np.divide(a, b) =>
 [[0.33333333 0.66666667]
 [0.75       1.        ]]



In [43]:
# Note what happens when the shapes don't match

a = np.array([1, 2, 3])
b = np.array([1, 2])

a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

NumPy also provides a bunch of super-useful functions to compute mathematical
functions of NumPy arrays, or do other common operations.
Some commonly used ones that you might find useful include:

In [44]:
a = np.array([1, 2, 3])

b = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([2, 3, 4])

d = np.array([[3, 4],
              [5, 6],
              [7, 8]])

In [45]:
# Sum all the elements in an array
np.sum(a)

6

In [46]:
# Sum elements along an axis/dimension
np.sum(b, axis=1)

array([ 6, 15])

In [47]:
# Take (natural) log element-wise
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [48]:
# Take exponential (e^x) element-wise
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [49]:
# Take square root element-wise
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [50]:
# Get maximum element in an array
print("np.max(a) = {}".format(np.max(a)))
print("np.max(b) = {}".format(np.max(b)))
print("np.max(b, axis=1) = {}".format(np.max(b, axis=1)))

np.max(a) = 3
np.max(b) = 6
np.max(b, axis=1) = [3 6]


In [51]:
# Get index of maximum element in an array
np.argmax(a)

2

In [52]:
# Get average of all elements in array
np.mean(a)

2.0

In [53]:
# Take a dot product between two arrays
# In this case, two vectors (1-D arrays)
np.dot(a, c)

20

In [54]:
# Matrix-multiply two arrays
print("b @ d =>\n {}\n".format(b @ d))
print("np.matmul(b, d) =>\n {}\n".format(np.matmul(b, d)))

b @ d =>
 [[34 40]
 [79 94]]

np.matmul(b, d) =>
 [[34 40]
 [79 94]]



In [55]:
# Get the norm (magnitude) of a matrix/vector
# You can specify different types of norm, but by default it does the
# 2-norm, which is only vector norm that we'll see in this class.
np.linalg.norm(a)

3.7416573867739413

__NOTE:__ In general, for most NumPy functions that operate on an entire array,
you can also specify a dimension or dimensions to apply it along

__NOTE:__ There are also other packages that build off of NumPy or
use NumPy arrays.
We'll very briefly encounter a few examples later in the class like SciPy
and PyTorch. For the most part, these packages tend to work very similarly to
the built-in NumPy functions above.

### Vectorization

In [88]:
arrays = np.random.random((1000, 1000))
other_array = np.random.random((1000))

In [92]:
%%time

#Compute the max inner product
max_i = 0
max_val = 0
for  i in range(1000):
    idp = 0
    for j in range(1000):
        idp += arrays[i][j] * other_array[j]
    if idp > max_val:
        max_val = idp
        max_i = i
print(max_i, max_val)
        


538 267.11303993265216
CPU times: user 667 ms, sys: 2.88 ms, total: 670 ms
Wall time: 670 ms


In [94]:
%%time

arrays = np.array(arrays)
other_array = np.array(other_array)
idps = np.dot(arrays, other_array)
print(np.argmax(idps), np.max(idps))


538 267.1130399326523
CPU times: user 3.35 ms, sys: 1.15 ms, total: 4.5 ms
Wall time: 1.61 ms


### Exercise 4 -- Broadcasting

A final topic that may be useful to you is broadcasting. It's one of the
most useful and powerful features of NumPy, because it lets you write matrix/
array operations in a natural way without having to be too specific
about what you want NumPy to do.

In most cases, NumPy can use broadcasting to infer what you wanted to do
and do it. Let's look at an example:

In [56]:
# Create a multi-dimensional (2 x 1) matrix of ones
a = np.ones((1,2))
a

array([[1., 1.]])

In [57]:
# Create a single-element 1-D array
b = np.array([4])
b

array([4])

Now recall that earlier, when we tried to add, multiply, subtract, etc. two
arrays, they had to have the same shape! Let's see what happens when we
do some of these things with a and b:

In [58]:
a + b

array([[5., 5.]])

In [59]:
a - b

array([[-3., -3.]])

In [60]:
a * b

array([[4., 4.]])

In [61]:
a / b

array([[0.25, 0.25]])

Wait, what happened?? We just said that the shapes had to match, but `a` and `b`
definitely don't have the same shape...

This is where broadcasting comes into play. Although `a` and `b` don't have the
same shape, they have __compatible__ shapes, so NumPy was able to guess
what we actually wanted to do and __broadcast__ behind the scenes to make the
operation work.

What NumPy did behind the scenes in this case is see that `b` and `a` don't have
the same shape, but also realize that maybe we meant to "re-use" the value in
`b` for every value in `a`. In other words, it "broadcast" `b` from its
original shape of (1,) to `a`'s shape of (2,) by duplicating the element
in `b`.

Once it did that, it could simply do the element-wise operation as usual!

This makes our life a lot easier, as we didn't have to explicitly write out
that duplication and reshaping ourselves. Of course, that assumes that this
behavior is actually what we intended.

In this case, it seems to make good sense, as if we tell it to subtract the
 array `[4]` from `[1, 1]`, it seems reasonable that what we are really asking
 for is for it to subtract 4 from each 1 in the second array.

Most of the time, NumPy assumes that whenever we do an operation on two arrays
with different shapes, we would like things to be broadcast if possible to
make the operation work.

It will then try to expand the smaller array to match the size of the bigger
one by copying/repeating the data in the smaller array.

Let's try a slightly more complicated example involving 2-D arrays:

In [62]:
# Create a 2-D array of shape (4, 3)
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
# Create an array of shape (4,)
# np.arange(n) creates a vector out of increasing
# integers from 0 to n (exclusive)
b = np.arange(4)

# Reshape to (4, 1)
b = b.reshape((4, 1))
b

array([[0],
       [1],
       [2],
       [3]])

In [64]:
# Multiply them together
b * a

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

Did it do what you expected? Do you see how broadcasting was applied to create
the result?

The details and different cases for broadcasting can be tricky, even
for experienced NumPy users! So you're certainly not expected to be use or need
it heavily in this class. However, knowing the basics of how it works may make
your life a little easier and your code a little simpler on some of the
homeworks.

If you ever find yourself in a confusing situation involving broadcasting, we
definitely recommend checking out the NumPy documentation/guide here:
https://numpy.org/doc/stable/user/basics.broadcasting.html

### Concluding Notes

That's it! That's all the basic NumPy knowledge you need for the
homeworks in this course (possibly you may not even need all of the tools we've
 introduced here).

If you're interested in learning more about NumPy, we recommend:
* The NumPy user guide (https://numpy.org/doc/stable/user/index.html)
* This CS 231n NumPy tutorial, which we based much of the content here on, but
which also contains some more advanced topics (https://cs231n.github.io/python-numpy-tutorial/#numpy)

If you found any issues/errors in the notebook, please let us know!

And if you have any further questions about using NumPy or confusion about any
of the examples in the notebook, stop by OH or post on Piazza and the
teaching staff will be happy to answer your questions!